name: meta-rauc CI

on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build:
    name: meta-rauc Build
    #runs-on: ${{ vars.BUILD_RUNS_ON || (github.repository == 'rauc/meta-rauc' && 'ptx-runner') || 'ubuntu-latest' }}
    runs-on: [self-hosted, forrest, build]
    timeout-minutes: 720
    steps:
      - name: Setup SSH Key for Yocto Cache
        run: |
          echo "${{ secrets.YOCTO_CACHE_KEY }}" >> ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          sudo mkdir -p /srv/cache /srv/shared-git
          sudo mount -t 9p cache /srv/cache || true
          sudo mount -t 9p shared-git /srv/shared-git || true
          df -h
          mkdir -p ~/.yocto
          echo 'SSTATE_MIRRORS = "file://.* file:///srv/cache/sstate-cache/PATH"' >> ~/.yocto/auto.conf
          echo 'INHERIT += "own-mirrors"' >> ~/.yocto/auto.conf
          echo 'SOURCE_MIRROR_URL = "http://10.0.2.2/downloads"' >> ~/.yocto/auto.conf
          echo 'INHERIT += "rm_work"' >> ~/.yocto/auto.conf
          # FIXME add OPKGBUILDCMD = 'opkg-build -Z gzip -a "-1n"'
      - name: Install required packages
        run: |
          sudo apt-get install diffstat
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: meta-rauc
      - name: Clone poky
        run: git clone --shared --reference-if-able /srv/shared-git/poky.git -b master https://github.com/yoctoproject/poky.git
      - name: Clone meta-openembedded
        run: git clone --shared --reference-if-able /srv/shared-git/meta-openembedded.git -b master https://github.com/openembedded/meta-openembedded.git
      - name: Initialize build directory
        run: |
          source poky/oe-init-build-env build
          bitbake-layers add-layer ../meta-rauc
          cp ~/.yocto/auto.conf conf/ || true
          echo 'INHERIT += "rm_work"' >> conf/local.conf
          echo 'DISTRO_FEATURES:remove = "alsa bluetooth usbgadget usbhost wifi nfs zeroconf pci 3g nfc x11 opengl ptest wayland vulkan"' >> conf/local.conf
      - name: Build rauc, rauc-native
        run: |
          source poky/oe-init-build-env build
          bitbake rauc rauc-native
      - name: Build rauc-hawkbit-updater
        run: |
          source poky/oe-init-build-env build
          bitbake rauc-hawkbit-updater
      - name: Build dt-utils
        run: |
          source poky/oe-init-build-env build
          bitbake dt-utils
      - name: Build casync, casync-native
        run: |
          source poky/oe-init-build-env build
          bitbake-layers add-layer ../meta-openembedded/meta-oe
          bitbake-layers add-layer ../meta-openembedded/meta-python
          bitbake-layers add-layer ../meta-openembedded/meta-networking
          bitbake-layers add-layer ../meta-openembedded/meta-filesystems
          bitbake casync casync-native
      - name: Build rauc-hawkbit
        run: |
          source poky/oe-init-build-env build
          bitbake-layers add-layer ../meta-openembedded/meta-python
          bitbake rauc-hawkbit
      - name: Cache Data
        if: ${{ always() }}
        run: |
          test ! -s ~/.ssh/id_ed25519 || rsync -rvx --ignore-existing build/downloads yocto-cache: || true
          test ! -s ~/.ssh/id_ed25519 || rsync -rvx --ignore-existing build/sstate-cache yocto-cache: || true

